### ISSUE TITLE
Hi,jianhong Yin.怎么样用pynfs建立mount并且建立多tcp连接呢？

### ISSUE THREAD

**Issue by AlexKingGo** [tcler/linux-network-filesystems#3]
你好  Jianhong。
  抱歉打扰到你，我在用pynfs的时候遇到一些问题，看到您是pynfs的contributor，并且精通nfs, 就想问您一些问题。因为我最近在北京这边实习，要开发一个nfs4.1协议的压测工具，要在单节点客户端模拟高并发下和服务器的多tcp链接，遇到一些困难，主要因为之前在学校没有接触过。
   1.如何用pynfs模拟客户端挂载目录？我研究了一下pynfs，没有找到客户端挂载的过程。
   2.如何用pynfs单进程下启动多tcp链接？我试了一下，运行两个不同的testserver.py是可以创建多连接的，我的疑问在于，能否用多线程实现？需要改动enviroment初始化过程中的哪些属性或者变量呢？
   期待您慷慨的解答。
   祝好！

**Comment by tcler** [comment]
Hi Alex

pynfs 主要是用来测试协议正确性的，压力测试你可以直接使用上游社区的一些 通用的文件系统压力测试工具（比如 fsx stress-ng iozone 等），不需要自己开发。

我也没有深入研究过 pynfs 代码，对于你的问题:
A1: pynfs 在 user-space 实现了 nfs client ，不走 mount(2)，找 connect 调用的地方应该能找到。
A2: 如果不是 pNFS 的话，多 tcp 意味着 多个 mount(or client object); 是否可以多线程我不清楚，你自己试试吧。

Again: 如果要做压力测试 用 pynfs 方向完全是错的，建议先找开源的 通用文件系统 压力测试套件 用。

Jianhong

**Comment by tcler** [comment]
一个很老的文档: https://www.kernel.org/doc/ols/2006/ols2006v2-pages-275-294.pdf ，建议先看一下

**Comment by AlexKingGo** [comment]
很荣幸能得到前辈慷慨的答疑，资料很棒，希望以后能多和前辈交流。
再次非常感谢前辈指导。
祝好！


------------------ 原始邮件 ------------------
发件人: "tcler.yin"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 下午5:58
收件人: "tcler/linux-network-filesystems"<linux-network-filesystems@noreply.github.com>;
抄送: "北航张少卿"<292598389@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tcler/linux-network-filesystems] Hi,jianhong Yin.怎么样用pynfs建立mount并且建立多tcp连接呢？ (#3)




一个很老的文档: https://www.kernel.org/doc/ols/2006/ols2006v2-pages-275-294.pdf ，建议先看一下
